version: '2'

services:
  app:
    image: bugfire/lego-auto:0.4
    volumes:
      - "./config:/config:ro"
      - "./data:/data"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    build:
      context: .
